import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// @: root -> src -> ...
import MainBanner from "@/app/components/mainbanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ~ index.html; wrapper of page.tsx
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MainBanner
          name="Alejandre Jose R. San Pedro (Aljo)"
          title="MSIT Student | Psychometrician"
        />
        {/* page.tsx! */}
        {children}
      </body>
    </html>
  );
}
